export const contactsData = [
  {
    id: 1,
    name: "Fernando García",
    email: "fernando.garcia@empresa.com",
    initials: "FG",
    color: "bg-blue-500",
    phone: "612 345 678",
    company: "Tecnología S.A.",
    industry: "Tecnología",
    age: 34,
    employmentStatus: "Dependiente",
    lists: [
      { name: "Campaña NPS", color: "bg-green-600" },
      { name: "CX", color: "bg-blue-600" },
    ],
  },
  {
    id: 2,
    name: "María Rodríguez",
    email: "maria.rodriguez@empresa.com",
    initials: "MR",
    color: "bg-purple-500",
    phone: "623 456 789",
    company: "Finanzas Plus",
    industry: "Finanzas",
    age: 42,
    employmentStatus: "Directivo",
    lists: [{ name: "Proveedor salud", color: "bg-purple-600" }],
  },
  {
    id: 3,
    name: "Jesús Joffre",
    email: "jesus.joffre@hotmail.com",
    initials: "JJ",
    color: "bg-green-500",
    phone: "700 255 24",
    company: "Retail Innovación",
    industry: "Retail",
    age: 29,
    employmentStatus: "Empleado",
    lists: [
      { name: "Siniestros", color: "bg-green-600" },
      { name: "RPA", color: "bg-orange-600" },
    ],
  },
  {
    id: 4,
    name: "Carlos Eguez",
    email: "carlosex12@gmail.com",
    initials: "CE",
    color: "bg-orange-500",
    phone: "771 690 61",
    company: "Salud Integral",
    industry: "Salud",
    age: 38,
    employmentStatus: "Independiente",
    lists: [
      { name: "Auto xKm", color: "bg-red-600" },
      { name: "Auto", color: "bg-blue-600" },
    ],
  },
  {
    id: 5,
    name: "Lenny Mercado",
    email: "lennycasass@gmail.com",
    initials: "LM",
    color: "bg-red-500",
    phone: "700 152 09",
    company: "Educación Digital",
    industry: "Educación",
    age: 45,
    employmentStatus: "Directivo",
    lists: [
      { name: "Salud", color: "bg-blue-600" },
      { name: "Salud total", color: "bg-amber-600" },
    ],
  },
]
